#!/bin/bash

GRIND=(valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all --track-fds=yes)
BIN="./cub3D"
MAPDIR="assets/maps/"
OUTFILE="tests/test.txt"

> "$OUTFILE"

MAPS=($(find "$MAPDIR" -type f -name "*.cub"))

for map in "${MAPS[@]}"; do
{
	echo
	echo ">>>>>>>> $map <<<<<<<<"
	echo "                                                      |"
    "${GRIND[@]}" "$BIN" "$map"
	"$BIN" "$map"
	echo "                                                      |"
    echo "===== FIN DU TEST : $map ======"
	echo
} >> "$OUTFILE" 2>&1
done
